package org.igras.api.common.enums

enum class IgrasDecimalFields(name: String) {
    Date("Дата"),
    Time("Время"),
    AirTemperatureOutsideInCelsius("Температура воздуха снаружи, °С"),
    MaximumAirTemperatureInCelsius("Максимальная температура воздуха, °С"),
    MinimumAirTemperatureInCelsius("Минимальная температура воздуха, °"),
    AirHumidityOutsidePercent("Влажность воздуха снаружи, %"),
    DewPointInCelsius("Точка росы, °С"),
    WindSpeedInKmPerHour("Скорость ветра, км/ч"),
    DirectionOfTheWin("Направление ветра"),
    DistanceCoveredByTheWindDuringTheMeasurementTimeKM("Расстояние, пройденное ветром за время измерения, км"),
    MaximumWindSpeedInMilePerSec("Максимальная скорость ветра, м/с"),
    TheLargestDeviationOfTheWindDirection("Наибольшее отклонение направления ветра"),
    CoolingEffectOfTheWindInCelsius("Охлаждающий эффект ветра, °С"),
    HeatIndexHumidityEffectInCelsiusDecimal("Тепловой индекс (эффект влажности), °С"),
    IndexDecimalThermalOfTemperatureHumidityAndWindInCelsius("Индекс (тепловой эффект) температуры, влажности и ветра, °С"),
    IndexDecimalOfTemperatureHumiditySunAndWindInCelsius("Индекс температуры, влажности, солнца и ветра, °С (ощущение температуры)"),
    AtmosphericPressureInHpa("Атмосферное давление, гПа"),
    TotalPrecipitationInMM("Сумма осадков, мм"),
    IntensityOfPrecipitationMMPerHour("Интенсивность осадков, мм/час"),
    SolarRadiationWPerM2("Солнечная радиация, Вт/м2"),
    IntensityOfSolarEnergyLangley("Интенсивность солнечной энергии, Лэнгли (11,6 Вт*ч/м2)"),
    MaximumSolarRadiation("Максимальная солнечная радиация, Вт/м2"),
    UVIndexDecimal("Индекс ультрафиолетового излучения (0-16)"),
    DoseOfUVRadiation("Доза УФ-излучения, Вт*с/м2"),
    MaximumUVIndexDecimal("Максимальный индекс ультрафиолетового излучения"),
    DegreeOfHeating("Степень обогрева (необходимость отопления), градусо-день"),
    DegreeOfCooling("Степень охлаждения (необходимость кондиционирования), градусо-день"),
    TemperatureRoomInCelsius("Температура в помещении, °С"),
    HumidityRoomInCelsius("Влажность воздуха в помещении, °С"),
    DewPointRoomInCelsius("Точка росы в помещении, °С"),
    HeatIndexInTheRoomInCelsiusDecimal("Тепловой индекс (ощущение температуры) в помещении, °С"),
    EquilibriumMoistureContentPercent("Равновесное содержание влаги (в древесине), %"),
    AirDensityKgImCube("Плотность воздуха, кг/м3"),
    TemperatureOfTheSecondThermometerInCelsius("Температура второго термометра, °С");
    
//    "Unknown 1",
//    "Unknown 2",
//    "Unknown 3",
//    "Unknown 4",
//    "Эвапотранспирация, мм",
//    "Влажность почвы на глубине 5 см, мм",
//    "Влажнсть почвы на глубине 10 см, мм",
//    "Unknown 5",
//    "Unknown 6",
//    "Температура почвы на глубине 5 см, °С",
//    "Температура почвы на глубине 10 см, °С",
//    "Unknown 7",
//    "Unknown 8",
//    "Unknown 9",
//    "Unknown 10",
//    "Unknown 11",
//    "Unknown 12",
//    "Число измерений ветра",
//    "Число пакетов данных по скорости ветра",
//    "Процент приема радиосигнала",
//    "Интервал архивирования, мин"
}